### PR TITLE
feat(progress-project): Add actions and documentation

### PR DESCRIPTION
**Pull request by MaiaRojas**
This add  actions to use feedback and progress-project  GET/POST/PUT/DELETE endpoints, including:

- addFeedback. deleteFeedback, getFeedback, getFeedbackBySlug, and updateFeedback actions
- addProgressProject. deleteProgressProject, getProgressProject, and updateProgressProject actions
- getReviewerSurvey action
- Update Tests
- Update snapshot
- Documentation

### CODE REVIEW

**Comment by MeryCardenas23** [comment]
:thinking: Why did you change from ProjectFeedback to Feedback?

**Comment by MeryCardenas23** [comment]
I suggest making small changes to the commit messages :nerd_face: 
image

- refactor(actions): Update feedback and reviewer-survey ecfbcb8
- feat(actions): Add actions and documentation of progress-project 4b3eaa8
- test(actions): Add test for feedback and project-progress 9a8f9ef 
- refactor: Make enancement from review 10d58da

_Tip_: The last commit covers many changes, perhaps if a `rebase` is made, these changes are rearranged in the previous commits.

**Comment by MaiaRojas** [comment]
> * test(actions): Add test for feedback and project-progress

Done

**Comment by MaiaRojas** [comment]
>  Why did you change from ProjectFeedback to Feedback?

Se cambio el endpoint de `project-feedback` por `feedback` ya que nos dimos cuenta que pueden existir diferente tipos de feedbacks ejem: `sprint-checkout`, `project-checkout` y `project-feedback`
Usamos un schema genérico de `feedback`  y definimos a través de reviewerSurvey el tipo.

**Pull request merged**
